env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detepted
rules:
  semi:
    - error
    - always
  '@typescript-eslint/no-var-requires': 0
  #eslint no-useless-return: error
  react/props-types: off
  '@typescript-eslint/explicit-function-return-type': off
  #'no-unused-vars': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      #varIgnorePattern: '^_'
  prettier/prettier:
    - error
    # TypeScript での no-use-before-define を有効にする
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define':
    - error
